"""add_unmatched_reason_to_answers

Revision ID: 00deb9e35878
Revises: c2c3dbc1df55
Create Date: 2026-09-19 13:48:47.122610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00deb9e35878'
down_revision: Union[str, None] = 'c2c3dbc1df55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('unmatched_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'unmatched_reason')
    # ### end Alembic commands ###
